name: europharm_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ">=2.18.0"
  flutter: ">=3.3.0"

dependencies:
  another_flushbar: ^1.12.30
  another_xlider: ^3.0.1
  cached_network_image: ^3.3.0
  # camera: ^0.9.8+1
  # change_app_package_name: ^1.1.0
#  code_field: ^1.22.0
  # convex_bottom_bar: ^3.0.0
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.5
  # device_info: ^2.0.3
  # device_info_plus: ^3.2.2
  # device_preview: ^1.0.0
  dio: ^4.0.6
  dotted_line: ^3.2.2
  firebase_auth: ^4.14.1
  firebase_analytics: ^10.7.1
  firebase_core: ^2.31.1
  firebase_crashlytics: ^3.4.5
  firebase_dynamic_links: ^5.3.6
  firebase_messaging: ^14.9.3
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.1
  flutter_local_notifications: ^16.1.0
  fluttertoast: ^8.2.2
  flutter_localizations:
    sdk: flutter
  # flutter_masked_text: 0.8.0
  flutter_multi_formatter: ^2.8.0
  # flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.1.5
  freezed_annotation:
  get_it: ^7.2.0
  geolocator: ^10.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5+3
  intl: ^0.19.0
  json_annotation: ^4.7.0
  json_serializable: ^6.4.1
  liquid_pull_to_refresh: ^3.0.1
  loader_overlay: ^2.1.0
  logger: ^1.1.0
  mask_text_input_formatter: ^2.4.0
  meta: ^1.7.0
  mobile_scanner: ^3.5.2
  path_provider: ^2.0.11
  pin_code_fields: ^8.0.1
  provider: ^6.0.3
  # pull_to_refresh: ^2.0.0
  # qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  shared_preferences: ^2.2.1
  syncfusion_flutter_calendar: ^20.3.48
  syncfusion_flutter_datepicker: ^20.3.48
  syncfusion_localizations: ^20.3.48
  table_calendar: ^3.0.7
  url_launcher: ^6.2.4
  # video_player: ^2.3.0
  yandex_mapkit: ^3.0.3
  simple_gesture_detector: ^0.2.0
  flutter_spinkit: ^5.2.0
  animated_icon: ^0.0.5
  assets_audio_player: ^3.1.1
  haptic_feedback: ^0.4.2
  mockito: ^5.4.2
  flutter_blurhash: ^0.7.0
  search_choices: ^2.2.7
  searchable_listview: ^2.8.0
  auto_route: ^7.8.4
  firebase_admin: ^0.2.0-dev.7
  flutter_pdfview: ^1.3.2
  easy_pdf_viewer: ^1.0.7
  advance_pdf_viewer2: ^2.0.5+1
  typed_data: ^1.3.2
  auto_size_text: ^3.0.0
  overlay_support: ^2.1.0

dev_dependencies:
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  freezed: ^2.1.1
  lint: ^1.10.0

flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/png/
    - assets/sound/done.mp3
    - assets/sound/error.mp3

  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: fonts/Gilroy-Semibold.ttf
          weight: 600
        - asset: fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: fonts/Gilroy-Regular.ttf
          weight: 300
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Bold.ttf
          weight: 700
        - asset: fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: fonts/ProductSans-Regular.ttf
          weight: 300
flutter_intl:
  enabled: true
